### ISSUE TITLE
An alternative way to pass customized parameters into eCPI

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-softlayer-cpi#163]
Since Env is cleaned up when BOSH invoke eCPI, we can't customize some properties (like SoftLayer API endpoint) through environment variables. Seems the only way to do such customization is through CPI configuration, defining in bosh-init yaml and setting in cpi.json eventually. So I plan to update eCPI code to accept such parameters from CPI configuration, and set these parameters as environment variables, so that softlayer-go can get and use these values through environment variables properly. I would like to set following parameters into softlayer section in bosh-init yaml:

```
    softlayer:
        apiEndpoint: api.service.softlayer.com
        apiWaitTime: 3 #seconds
        apiRetryCount: 5  #times
        createIscsiVolumeTimeout: 900 #seconds
        createIscsiVolumePollingIntertval: 15 #seconds
```

@maximilien Please let me know if you have any comment. Thanks.
