### ISSUE TITLE
What should the mbus URL be when standing up a director with bosh-init?

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi#168]
I'm attempting to bring up a director with the newest CPI, bosh, and stemcell and it's failing because `bosh-init` is unable to ping the agent on the VM that the CPI created.

It appears `bosh-init` is using the cloud_provider.mbus URL to perform the ping. How do I configure the URL in the manifest when I don't know the address of the VM that will be brought up by the CPI?

The one example that's in the release repository appears to use a DNS resolvable host name but that seems like a chicken-and-egg problem.

What's the correct way to do this?

**Comment by mattcui** [comment]
@sykesm To support OS reload, we have to do some tricks in bosh-init and CPI code, as you guessed, there needs to specify the hostname with <VmNamePrefix>.<Domain>, for example:

```
  cloud_properties:
    Domain: softlayer.com
    VmNamePrefix: director-fake-for-demo
...
cloud_provider:
  template: {name: softlayer_cpi, release: bosh-softlayer-cpi}

  # Tells bosh-init how to contact remote agent
  mbus: https://admin:admin@director-fake-for-demo.softlayer.com:6868
```

CPI will set an entry in /etc/hosts to map this hostname to the real IP.
