### ISSUE TITLE
`bosh deploy` fails when `Waiting for the agent on VM`

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/bosh-softlayer-cpi#187]
When I try to deploy a new bosh director in Softlayer using `bosh-init`, I get the error `Post https://admin:[PASSWORD-REMOVE]@bosh-softlayer.softlayer.com:6868/agent: dial tcp: lookup bosh-softlayer.softlayer.com on 9.152.120.241:53: no such host`

How can I fix this?

**Full log:**

```shell
$ bosh-init deploy ./bosh.yml
Deployment manifest: '/Users/pego/workspace/my-bosh/bosh.yml'
Deployment state: '/Users/pego/workspace/my-bosh/bosh-state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:01)
  Validating release 'bosh-softlayer-cpi'... Finished (00:00:01)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:02)

Started installing CPI
  Compiling package 'golang_1.7.1/591034a93e2a5aaf008f76b69a1f23fc61e642d8'... Finished (00:00:00)
  Compiling package 'bosh_softlayer_cpi/2933b13c68cb998aae4bb03a899a759dbcc65d07'... Finished (00:00:00)
  Installing packages... Finished (00:00:04)
  Rendering job templates... Finished (00:00:00)
  Installing job 'softlayer_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:05)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-softlayer-xen-ubuntu-trusty-go_agent/3312.12'... Skipped [Stemcell already uploaded] (00:00:00)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell '1443361'... Finished (00:08:32)
  Waiting for the agent on VM '27250573' to be ready... Failed (00:09:59)
Failed deploying (00:18:32)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Waiting until instance is ready:
        Sending ping to the agent:
          Performing request to agent endpoint 'https://admin:[PASSWORD-REMOVED]@bosh-softlayer.softlayer.com:6868/agent':
            Performing POST request:
              Post https://admin:[PASSWORD-REMOVED]@bosh-softlayer.softlayer.com:6868/agent: dial tcp: lookup bosh-softlayer.softlayer.com on 9.152.120.241:53: no such host
```

**`bosh.yml`:**

```yaml
---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=260.1
  sha1: 7fb8e99e28b67df6604e97ef061c5425460518d3
- name: bosh-softlayer-cpi
  url: file:///Users/pego/workspace/bosh-softlayer-cpi-release/dev_releases/bosh-softlayer-cpi/bosh-softlayer-cpi-3.0.5+dev.7.tgz

resource_pools:
- name: vms
  network: default
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-softlayer-xen-ubuntu-trusty-go_agent?v=3312.12
    sha1: 8416bb3191065670e3220331333caecf7c23d884
  cloud_properties:
    Domain: softlayer.com
    VmNamePrefix: bosh-softlayer
    EphemeralDiskSize: 100
    StartCpus: 4
    MaxMemory: 8192
    Datacenter:
      Name: dal09
    HourlyBillingFlag: true
    PrimaryNetworkComponent:
      NetworkVlan:
        Id: 1113225
    PrimaryBackendNetworkComponent:
      NetworkVlan:
        Id: 1113235
    NetworkComponents:
    - MaxSpeed: 1000

disk_pools:
- name: disks
  disk_size: 40_000

networks:
- name: default
  type: dynamic
  dns: [8.8.8.8]

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: powerdns, release: bosh}
  - {name: softlayer_cpi, release: bosh-softlayer-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: default

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: [PASSWORD-REMOVED]

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: [PASSWORD-REMOVED]
      database: bosh
      adapter: postgres

    blobstore:
      address: 127.0.0.1
      port: 25250
      provider: dav
      director:
        user: director
        password: [PASSWORD-REMOVED]
      agent:
        user: agent
        password: [PASSWORD-REMOVED]

    director:
      address: 127.0.0.1
      name: bosh
      cpi_job: softlayer_cpi
      db: *db
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: [PASSWORD-REMOVED]}
          - {name: hm, password: [PASSWORD-REMOVED]}

    hm:
      director_account:
        user: hm
        password: [PASSWORD-REMOVED]
      resurrector_enabled: true

    dns:
      address: 127.0.0.1
      domain_name: bosh
      db: *db
      webserver:
        port: 8081
        address: 0.0.0.0

    softlayer: &softlayer
      username: [USERNAME-REMOVED]
      apiKey: [API-KEY-REMOVED]

    agent: {mbus: "nats://nats:[PASSWORD-REMOVED]@bosh-softlayer.softlayer.com:4222"}

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: softlayer_cpi, release: bosh-softlayer-cpi}

  mbus: https://admin:[PASSWORD-REMOVED]@bosh-softlayer.softlayer.com:6868

  properties:
    softlayer: *softlayer
    agent: {mbus: "https://admin:[PASSWORD-REMOVED]@bosh-softlayer.softlayer.com:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
```

cc @suhlig @smoser-ibm
